name: Build and Format

on: [push]

jobs:
  build-and-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - run: rustup show

      - name: Install rustfmt and clippy
        run: |
          rustup component add rustfmt
          rustup component add clippy

      - uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae # v2

      - name: Install Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 18

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@8f1998e9878d786675189ef566a2e4bf24869773 # v1.2.0
        with:
          version: nightly-0079a1146b79a4aeda58b0258215bedb1f92700b

      - name: Build contracts
        working-directory: packages/contracts
        run: yarn build

      - name: Build and check for warnings
        env:
          RUSTFLAGS: "-D warnings"
        run: cargo build --release

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Run clippy
        run: cargo clippy -- -D warnings
